// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, unused_import
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKQHGAi65vTVb8QMuyNTevVVzru-Zh60',
    appId: '1:269604310634:web:6df59986889a00ed73c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    authDomain: 'thanhhoa-5b7f5.firebaseapp.com',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
    measurementId: 'G-G3MZB97GH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_C_fOl-xN9dwVXUO8Is_EyhdcvuayNOg',
    appId: '1:269604310634:android:5bc30acb0c838f8773c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6pPIrr4AIl_td_ODRVG8Cdc_F16dSnb0',
    appId: '1:269604310634:ios:aa381f5568ba8eb773c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
    iosClientId:
        '269604310634-p1qq5effchjji9h7rei87fr5gf1v6grg.apps.googleusercontent.com',
    iosBundleId: 'com.example.thanhhoaGarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6pPIrr4AIl_td_ODRVG8Cdc_F16dSnb0',
    appId: '1:269604310634:ios:aa381f5568ba8eb773c413',
    messagingSenderId: '269604310634',
    projectId: 'thanhhoa-5b7f5',
    storageBucket: 'thanhhoa-5b7f5.appspot.com',
    iosClientId:
        '269604310634-p1qq5effchjji9h7rei87fr5gf1v6grg.apps.googleusercontent.com',
    iosBundleId: 'com.example.thanhhoaGarden',
  );
}
